name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:    
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '6.0.x'
            include-prerelease: true
      - run: dotnet run --project src/visose.Web/visose.Web.csproj
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_SITE }}          
          action: "upload"
          app_location: "/artifacts/output"
          skip_app_build: true